# Generated by Django 2.0.7 on 2021-05-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suv',
            field=models.TextField(blank=True),
        ),
    ]
